language: node_js
node_js:
  - "10"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --only hosting --token "1/MSvLBuLUf9xUaTVHhK-SMYc4LjLRXdIPWFfAeB2tKHk"
branches:
  only:
    - master